version: '2'

services:
  proxy:
      build: .
      image: proxy
      volumes:
            - "./HTTPProxy:/HTTPProxy"
            - "./logs:/var/log/erss"
      ports:
            - "12345:12345"
      command: bash -c "make && ./proxy&& while true; do continue; done"
